"""phase 17: accounts, sessions, user_id/saved on jobs and batches

Revision ID: 15e378e8a7eb
Revises: 930d6e0d0620
Create Date: 2026-09-12 16:53:13.802447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e378e8a7eb'
down_revision: Union[str, Sequence[str], None] = '930d6e0d0620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('batches', sa.Column('user_id', sa.String(length=32), nullable=True))
    op.add_column('jobs', sa.Column('user_id', sa.String(length=32), nullable=True))
    # server_default is required here, not optional -- unlike every
    # nullable column this project has added to an existing table
    # before it (e.g. `target`), this is the first NOT NULL one, and
    # both SQLite and Postgres need a real value to backfill existing
    # rows with when adding a NOT NULL column, not just the Python-side
    # `default=False` on the ORM model (which only ever applies to a
    # future INSERT, never to rows that already exist). Confirmed the
    # hard way: autogenerate's own output omits this and fails outright
    # against a database that already has job rows.
    op.add_column(
        'jobs', sa.Column('saved', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'saved')
    op.drop_column('jobs', 'user_id')
    op.drop_column('batches', 'user_id')
    op.drop_table('users')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
