"""phase 18: is_admin on users, audit_log table

Revision ID: 8853528f6c4e
Revises: 15e378e8a7eb
Create Date: 2026-09-12 20:20:50.762183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8853528f6c4e'
down_revision: Union[str, Sequence[str], None] = '15e378e8a7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default required -- see the almost-identical note on
    # JobRecord.saved's own migration (15e378e8a7eb): a NOT NULL column
    # added to a table that may already have real rows (any account
    # created since Phase 17 shipped) needs a real backfill value, which
    # a Python-side `default=False` on the ORM model never provides for
    # a row that already exists.
    op.add_column(
        'users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
