"""add target to jobs

Revision ID: 930d6e0d0620
Revises: 70e8437d9b06
Create Date: 2026-09-09 13:49:53.116773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930d6e0d0620'
down_revision: Union[str, Sequence[str], None] = '70e8437d9b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('target', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'target')
    # ### end Alembic commands ###
